# Generated by Django 2.2.2 on 2019-09-02 14:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('billing', '0002_auto_20190711_1506'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address_type', models.CharField(default='shipping', max_length=120)),
                ('name', models.CharField(max_length=120)),
                ('mobile', models.CharField(max_length=120)),
                ('payment', models.CharField(choices=[('-', '-'), ('cash', 'Наличными'), ('credit_card', 'Карточкой')], default='-', max_length=120)),
                ('address', models.TextField(max_length=120)),
                ('city', models.CharField(default='Минск', max_length=120)),
                ('region', models.CharField(choices=[('Brest', 'Брестская область'), ('Vitebsk', 'Витебская область'), ('Gomel', 'Гомельская область'), ('Grodno', 'Гродненская область'), ('Minsk', 'Минская область'), ('Mogilev', 'Могилевская область')], default='Minsk', max_length=120)),
                ('postal_code', models.CharField(max_length=120)),
                ('billing_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='billing.BillingProfile')),
            ],
        ),
    ]
