# Generated by Django 2.2.2 on 2019-07-24 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addresses', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='address_line_1',
            new_name='mobile',
        ),
        migrations.RemoveField(
            model_name='address',
            name='address_line_2',
        ),
        migrations.RemoveField(
            model_name='address',
            name='address_type',
        ),
        migrations.AddField(
            model_name='address',
            name='address',
            field=models.TextField(default='Belarus', max_length=120),
        ),
        migrations.AddField(
            model_name='address',
            name='name',
            field=models.CharField(default='Ivan', max_length=120),
        ),
        migrations.AddField(
            model_name='address',
            name='region',
            field=models.CharField(choices=[('Brest', 'Брестская область'), ('Vitebsk', 'Витебская область'), ('Gomel', 'Гомельская область'), ('Grodno', 'Гродненская область'), ('Minsk', 'Минская область'), ('Mogilev', 'Могилевская область')], default='Minsk', max_length=120),
        ),
    ]
