# Generated by Django 2.2.2 on 2019-07-24 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addresses', '0002_auto_20190724_1338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='address',
            field=models.TextField(max_length=120),
        ),
        migrations.AlterField(
            model_name='address',
            name='city',
            field=models.CharField(default='Minsk', max_length=120),
        ),
        migrations.AlterField(
            model_name='address',
            name='name',
            field=models.CharField(max_length=120),
        ),
    ]
