# Generated by Django 2.2.2 on 2019-09-25 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('addresses', '0003_auto_20190903_1310'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='payment',
        ),
    ]
