# Generated by Django 2.2.2 on 2019-07-24 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addresses', '0005_address_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='payment',
            field=models.CharField(choices=[('-', '-'), ('cash', 'Наличными'), ('credit_card', 'Карточкой')], default='-', max_length=120),
        ),
    ]
