# Generated by Django 2.2.2 on 2019-07-24 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addresses', '0006_auto_20190724_1501'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='address_type',
            field=models.CharField(default='shipping', max_length=120),
        ),
    ]
