# Generated by Django 2.2.2 on 2019-07-25 10:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_auto_20190711_1506'),
        ('addresses', '0009_auto_20190725_1224'),
    ]

    operations = [
        migrations.CreateModel(
            name='BillingAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address_type', models.CharField(default='billing', max_length=120)),
                ('card_number', models.PositiveIntegerField(max_length=16)),
                ('security_code', models.PositiveIntegerField(max_length=3)),
                ('expiration_date', models.DateField()),
                ('postal_code', models.CharField(max_length=120)),
                ('billing_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='billing.BillingProfile')),
            ],
        ),
    ]
