# Generated by Django 2.2.2 on 2019-07-25 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addresses', '0010_billingaddress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billingaddress',
            name='card_number',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='billingaddress',
            name='security_code',
            field=models.PositiveIntegerField(),
        ),
    ]
