# Generated by Django 2.2.2 on 2019-07-20 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_auto_20190718_1330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('created', 'Создан'), ('paid', 'Оплачен'), ('shipped', 'Доставлен'), ('refunded', 'Возврат')], default='created', max_length=120),
        ),
    ]
