# Generated by Django 2.2.2 on 2019-08-16 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_auto_20190620_1141'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='author_year',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(blank=True, choices=[('russian', 'Русская классическая литература'), ('foreign', 'Зарубежная классическая литература'), ('detective', 'Детектив'), ('fantasy', 'Фантастика, фэнтези'), ('belarus', 'Белорусская литература')], max_length=250, null=True),
        ),
    ]
