# Generated by Django 2.2.2 on 2019-08-19 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_auto_20190816_1300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(blank=True, choices=[('russian', 'Русская классическая литература'), ('foreign', 'Зарубежная классическая литература'), ('detective', 'Детектив'), ('fantasy', 'Фантастика, фэнтези')], max_length=250, null=True),
        ),
    ]
